name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
      - name: update-databricks-repo
        shell: bash
        env:
          DATABRICKS_HOST : ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN : ${{ secrets.DB_TOKEN }}
        run: |
          databricks repos update --branch master --path "/Repos/skamalj@outlook.com/databricks.git" 